### ISSUE TITLE
Combat currently costs nothing, rewards heavily reduced

### ISSUE THREAD

**Issue by mightyagrippa** [Morpheox/Kraft#66]
This recent pr seems to have made some unintended changes to combat:
https://github.com/Morpheox/Kraft/commit/e057778e074229711037a7736d784caa79d5d2ee

There is no morale cost, food cost, or any cost at all for combat. Lines 531-535 of the old main.js didn't move to the new combat.js and so nothing is decrementing your morale and such.

Diamonds no longer drop from combat, lines 1057-1060 of the old main.js were removed and that took them off the loot table.

Artifacts no longer drop from combat, same thing but lines 1062-1064.

Heirloom drop rate was reduced by a factor of 10, from a >.99 roll to a >.999 roll.

**Comment by Morpheox** [comment]
Reverted until its fixed, please test your pull requests before asking for merging, i dont have much time to test them.

**Comment by mightyagrippa** [comment]
Thanks for the quick response! You've got a great game here.
