### ISSUE TITLE
Technologies and buildings available without the requirements met

### ISSUE THREAD

**Issue by Halithor** [Morpheox/Kraft#70]
Many of the technologies and buildings may be built without the proper requirements being met. While the buttons are all hidden properly, trying to build using the `build();` method can still build structures like the foundry when you have the resources available, but not the technology. 

For example, Copper Tools may be researched by calling jQuery's `$.click()` on the button, even when I do not have a Library (the button is properly hidden though).

While this does not affect most users, I enjoy writing an AI to play the game for me and being able to build and research before I meet the requirements feels a little like cheating.

**Comment by Morpheox** [comment]
You can alter everything in the game using jquery, the game its not cheat-protected since the code is running locally in your machine. There is nothing i can do other than to remake the game in flash or make it run server-side.
